server:
  port: 8080  # Porta onde o API Gateway vai rodar

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: task-service
          uri: lb://TASK-SERVICE
          predicates:
            - Path=/tasks/**
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**

management:
  endpoints:
    web:
      exposure:
        include: health
